### ISSUE TITLE
Edit generate_features() in core.py to work on every df in self.train and self.test

### ISSUE THREAD

**Issue by jtanwk** [satejsoman/chicago-business-viability#20]
Assume self.train and self.test are lists of license-level data.

For each df in self.train and self.test,
1. transform to business-year
2. create label and any features that start from license level data
3. create features that start from business-year level data 
4. overwrite df with new business-year df

Then run_model() stage can work on every element in self.train or self.test as needed.

**Comment by jtanwk** [comment]
@satejsoman @murray-cecile this is how i'm planning to modify the pipeline to work for multiple test-train splits, fyi

**Comment by satejsoman** [comment]
i think you should start branch from master for this after #19 has merged

**Comment by jtanwk** [comment]
Addressed in #30 pending review
