### ISSUE TITLE
extract best model from evaluation csv

### ISSUE THREAD

**Issue by murray-cecile** [satejsoman/chicago-business-viability#37]

**Comment by murray-cecile** [comment]
@satejsoman, were you thinking of something that does this automatically as part of the pipeline, or that does it after the fact? I could integrate it into evaluation.py and call it in core.py and put the result in the pipeline.run file or something, but maybe you were thinking of something we'd use more interactively. I wrote a little function to grab the best metric-at-k from your evaluations.csv (not pushed) but would be curious to know what you and @jtanwk  would find most helpful

**Comment by jtanwk** [comment]
Thanks for working on this! I think the mvp would be just to print a result to stdout or write some output file for sure. Like a table of the best 1-5 models + parameters for a specified metric-at-k (or even hardcoded at this stage, just as a helper for us for interpretation). 

The heuristic I had in mind for "best model" was "highest average metric-at-k over all temporal test/train splits" and hope it does fairly consistently over each split. A direct upgrade would be to plot it (like the chart that Rayid showed us for model performance over several year splits).
